// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQjDugtoRJXZcOSOSA6DWa0OFcVHyqMQE',
    appId: '1:766049360094:web:874145ad01daab62d74a4f',
    messagingSenderId: '766049360094',
    projectId: 'wagba-68535',
    authDomain: 'wagba-68535.firebaseapp.com',
    storageBucket: 'wagba-68535.appspot.com',
    measurementId: 'G-RY0Z1Z34D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrO7papytTS97WjRJiwxFVCNxTzOQ4ifQ',
    appId: '1:766049360094:android:4f8a4a8ed49216fad74a4f',
    messagingSenderId: '766049360094',
    projectId: 'wagba-68535',
    storageBucket: 'wagba-68535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc5UQPoB5OjlUh3Tq9hTe-JNoll06jbxg',
    appId: '1:766049360094:ios:17aa18a9ed429486d74a4f',
    messagingSenderId: '766049360094',
    projectId: 'wagba-68535',
    storageBucket: 'wagba-68535.appspot.com',
    iosBundleId: 'com.example.wagba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc5UQPoB5OjlUh3Tq9hTe-JNoll06jbxg',
    appId: '1:766049360094:ios:17aa18a9ed429486d74a4f',
    messagingSenderId: '766049360094',
    projectId: 'wagba-68535',
    storageBucket: 'wagba-68535.appspot.com',
    iosBundleId: 'com.example.wagba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQjDugtoRJXZcOSOSA6DWa0OFcVHyqMQE',
    appId: '1:766049360094:web:8b53638513ce0927d74a4f',
    messagingSenderId: '766049360094',
    projectId: 'wagba-68535',
    authDomain: 'wagba-68535.firebaseapp.com',
    storageBucket: 'wagba-68535.appspot.com',
    measurementId: 'G-GZRFNK7GQE',
  );
}
